{% set name = "wera2netcdf" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wera2netcdf-{{ version }}.tar.gz
  sha256: 85166a119a1529b7cbbf50b2f25a10369826ad3527f8549dcd95a83ac2b331d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

test:
  imports:
    - wera2netcdf
    - wera2netcdf.tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/wera2netcdf
  license: MIT
  summary: 'A utility to convert WERA total ASCII files into CF NetCDF files.'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
