{% set version = "1.0.0" %}

package:
  name: wera2netcdf
  version: {{ version }}

source:
  fn: wera2netcdf-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/wera2netcdf/archive/{{ version }}.tar.gz
  sha256: eb3b37ee163cc4fbbba032f9ae3279eac582fa87d2b0d741a993abb2c947c36a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

test:
  imports:
    - wera2netcdf
    - wera2netcdf.tests
  requires:
    - pytest

about:
  home: https://github.com/axiom-data-science/wera2netcdf
  license: MIT
  summary: 'A utility to convert WERA total ASCII files into CF NetCDF files.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
