# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WwUp6aSxY3y8UoYKF4SxcjnEUdYns1MdLe/Sp+3reZsse7QERX9yfE48Vz25OFBYwSQoHGgez9sOHtWz24DM3E08McYbP1xFX3hQl+MKi6s6yndx/yosodVf8f6RkOREXVAmZNL5h92fslcCyQy6X8x/uXnGZCcbf3dWoTmY562WOSg3563DTiPcWPWFadOSoX/N8wFoxTr4VWKJt9l33qSWi397FjcmduanR6Q3tJjQBrfIIX0QuDOK6BjknJhNOZFT1qWLnPcyOC6oy5zn61NI3KoMVSTOnsD+zErhaqkTtNHibTAySZPhaLLASJEzvP82LZGuIDi8mig7p17RkY7p/FWaBBJeCjyP4wbLfmXkx9+VtETud1MB1pr52HnyPMDU2YzMQqLWn106EXVNFfiAWj3GOHexfLFRnY62XpKQdBbB0QXQX67Y4i3o822rWdLN8c9TH8DjRaWPgigO0Dz60JzBUu8Mv7RTY9jDMsv1e9EaczrP/Oxy0AmD7w+bndmhd+6TfdM0JGRKDyy6nU26yB0lfJ3JRXUW/b3uqKdbwZvhgcAM/5cziQv2HxD3ai7J/BYPc1V7H+UXeGK1qF56uYFW+WfAhiPqT/qiw4XKhk2b4QIyWNqhZoOwashSPm4iBOPHP6I8bOWiYgcEb/vILPNvLo75JZZGgu8uliw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
