travis:
  secure:
    BINSTAR_TOKEN: HSYv9i2ozMx8s3gBgEqQV/i3QRTTqrO3dq1VxYd9PolhxZvnLQ05EaoVS32u/Po7F/ZjvUCwmxi/bkLnQJ75TrtIkKMq3v0owYQf7Q9YfT6iuZOpGkGz13XMO9LblGHFjU49jYuuf1Er86g1NSgGzFFp+XPkBmwGKU9SB3rlyfPcCy5FLtDGxYnKJvxqF8Mqkaq4luz4lbgrj57HCYipUiU8mCCvoah0/wsr2/bhZzdxrHJ4/geI64THlr9FJ16E7b2y8jPAkANAZov2AaU9feSo7AbMu/SqvZHKq2DfRsxfaXeETQb9iOxXH8fqNj6WE1HzOo6Y58GQgtaUfYd/ASZ3lIXlIEyytuLbs0U82XCS1k7pKEgT2hP9fuQ6Am8t2hsEilUmkHrPqz3w8lqYeON8J+mwhUQIexZm+7TpEyuD9lnncbF6GIE4ApB+a9TiOfzwB/qJg7vJoJNN3kOOQ14zXp8SD5FPCCCz99i93i/Maoe/D4Qv2fuaHzIkRMRWh8bxdiwdSZo9ocC6K+ZGMuhph1SuUo5Az850/MfzKdKqllH47x3UTwq2HmOwHCD3vXjZHYToDFe+91YDjIg4JsXCSjE+gh0W7qmFOnApKNZdVtYOaH5vOZ5eL34PiJi3RBjcRg1SB3vWA1ItA6WugbacEe2cmzaPP4hFQmvzxTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
