travis:
  secure:
    BINSTAR_TOKEN: WwUp6aSxY3y8UoYKF4SxcjnEUdYns1MdLe/Sp+3reZsse7QERX9yfE48Vz25OFBYwSQoHGgez9sOHtWz24DM3E08McYbP1xFX3hQl+MKi6s6yndx/yosodVf8f6RkOREXVAmZNL5h92fslcCyQy6X8x/uXnGZCcbf3dWoTmY562WOSg3563DTiPcWPWFadOSoX/N8wFoxTr4VWKJt9l33qSWi397FjcmduanR6Q3tJjQBrfIIX0QuDOK6BjknJhNOZFT1qWLnPcyOC6oy5zn61NI3KoMVSTOnsD+zErhaqkTtNHibTAySZPhaLLASJEzvP82LZGuIDi8mig7p17RkY7p/FWaBBJeCjyP4wbLfmXkx9+VtETud1MB1pr52HnyPMDU2YzMQqLWn106EXVNFfiAWj3GOHexfLFRnY62XpKQdBbB0QXQX67Y4i3o822rWdLN8c9TH8DjRaWPgigO0Dz60JzBUu8Mv7RTY9jDMsv1e9EaczrP/Oxy0AmD7w+bndmhd+6TfdM0JGRKDyy6nU26yB0lfJ3JRXUW/b3uqKdbwZvhgcAM/5cziQv2HxD3ai7J/BYPc1V7H+UXeGK1qF56uYFW+WfAhiPqT/qiw4XKhk2b4QIyWNqhZoOwashSPm4iBOPHP6I8bOWiYgcEb/vILPNvLo75JZZGgu8uliw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
